POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "media",
    "marcadores": [
        {"local": "ifsc"},
        {"acao": "olhando"},
         {"nome": "lucas.bernardo"},
          {"perfil": "aluno"}
    ],
    "valores": [
        {"ier": -5},
        {"tip": 8},
        {"arc": 8}
    ]
    
}